# Generated by Django 3.0.14 on 2022-02-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('first_name', models.CharField(max_length=50, verbose_name='first_name')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='middle_name')),
                ('surname', models.CharField(max_length=50, verbose_name='surname')),
                ('age', models.IntegerField(verbose_name='age')),
                ('birthday', models.DateField(verbose_name='birthday')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-Binary'), ('T', 'Transgender'), ('I', 'Intersex'), ('IPNTS', 'I prefer not to say')], default='Male', max_length=50, verbose_name='gender')),
                ('email_address', models.EmailField(max_length=50, verbose_name='email_address')),
                ('home_address', models.CharField(max_length=50, verbose_name='home_address')),
                ('borrower_code', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True, verbose_name='borrower_code')),
                ('valid_id', models.ImageField(upload_to='D:\\SchoolWorks\\CPET12L\\WebApplication\\ourProject\\Image Files\\Valid ID', verbose_name='valid_id')),
            ],
            options={
                'db_table': 'dragonladyApp_Registration',
            },
        ),
    ]
