# Generated by Django 3.0.14 on 2022-02-08 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonladyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField(verbose_name='loan_date')),
                ('amount_of_loan', models.IntegerField(verbose_name='amount_of_loan')),
                ('to_be_paid', models.IntegerField(verbose_name='to_be_paid')),
                ('due_date', models.DateField(verbose_name='due_date')),
                ('mode_of_loan_transfer', models.CharField(choices=[('GC', 'Gcash'), ('PM', 'Paymaya'), ('PP', 'Paypal'), ('BDO', 'BDO'), ('WI', 'Walk-In')], default='Gcash', max_length=50, verbose_name='mode_of_loan_transfer')),
                ('borrower_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonladyApp.Registration')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowerLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonladyApp.Registration')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='payment_date')),
                ('to_be_paid', models.IntegerField(verbose_name='to_be_paid')),
                ('amount_paid', models.IntegerField(verbose_name='amount_paid')),
                ('remaining_balance', models.IntegerField(verbose_name='remaining_balance')),
                ('mode_of_payment', models.CharField(blank=True, choices=[('GC', 'Gcash'), ('PM', 'Paymaya'), ('PP', 'Paypal'), ('BDO', 'BDO'), ('WI', 'Walk-In')], default='Gcash', max_length=50, verbose_name='mode_of_payment')),
                ('proof_of_payment', models.ImageField(blank=True, upload_to='D:\\SchoolWorks\\CPET12L\\WebApplication\\ourProject\\Image Files\\Proof of Payment', verbose_name='proof_of_payment')),
                ('borrower_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonladyApp.ApplyLoan')),
            ],
        ),
    ]
