# Generated by Django 3.0.14 on 2022-02-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonladyApp', '0002_applyloan_applypayment_borrowerlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyloan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applypayment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
