# Generated by Django 3.0.14 on 2022-02-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonladyApp', '0003_auto_20220208_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applypayment',
            name='proof_of_payment',
            field=models.ImageField(blank=True, upload_to='D:\\SchoolWorks\\CPET12L\\WebApp\\ourProject\\Image Files\\Proof of Payment', verbose_name='proof_of_payment'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='valid_id',
            field=models.ImageField(upload_to='D:\\SchoolWorks\\CPET12L\\WebApp\\ourProject\\Image Files\\Valid ID', verbose_name='valid_id'),
        ),
    ]
